services:
  openwebui:
    # Image wählen:
    # - CPU: ghcr.io/open-webui/open-webui:main
    # - GPU: ghcr.io/open-webui/open-webui:cuda
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    environment:
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
    volumes:
      - openwebui_data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  openwebui_data:
